# Generated by Django 3.2.6 on 2021-09-21 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachee',
            name='outreached_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 21, 6, 22, 11, 256607)),
        ),
    ]
