# Generated by Django 3.2.6 on 2021-09-21 20:14

import casetracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetracker', '0009_alter_applicant_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='enrollment_key',
            field=models.BigIntegerField(verbose_name=casetracker.models.random_string),
        ),
    ]
