# Generated by Django 3.2.6 on 2021-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetracker', '0010_alter_applicant_enrollment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='enrollment_key',
            field=models.BigIntegerField(default='5960731985034173'),
        ),
    ]
