# Generated by Django 3.2.6 on 2021-09-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetracker', '0017_auto_20210924_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to='casetracker.project'),
        ),
        migrations.AlterField(
            model_name='outreachee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Outreachee', to='casetracker.project'),
        ),
    ]
