# Generated by Django 3.2.6 on 2021-09-25 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetracker', '0020_auto_20210924_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='enrolled_date',
            field=models.DateField(default=datetime.date(2021, 9, 25)),
        ),
        migrations.AlterField(
            model_name='outreachee',
            name='outreached_date',
            field=models.DateField(default=datetime.date(2021, 9, 25)),
        ),
    ]
