# Generated by Django 3.2.6 on 2021-08-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resources',
        ),
    ]
